name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build:
    runs-on: windows-latest  # Use Windows for .exe build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller master_image_template_generation.spec --exclude-module pathlib
      

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-file
          path: dist/master_image_template_generation.exe
